# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dzHwLo8ZVwzuRArpNjfwUgAQs2Kl2PUQ
"""

import pandas as pd
import sqlite3
from google.colab import files

df = pd.read_csv('/content/hr_data.csv')

# 2. Clean column names (Remove spaces)
df.columns = df.columns.str.replace(' ', '')

# 3. Create a database file
conn = sqlite3.connect('Project_Data.db')

# 4. Save data into the database
df.to_sql('employees', conn, if_exists='replace', index=False)
conn.close()

print("Database created! Downloading now...")

# 5. Download the database to your computer
files.download('Project_Data.db')